version: 0.0.1.{build}

shallow_clone: true

image: Visual Studio 2017

cache:
  - "%APPDATA%\\stack"
  - .stack-work

build_script:
  - choco install haskell-stack
  - mkdir "%APPDATA%\\stack"
  - stack --no-terminal --skip-msys setup > NUL
  - mklink /D %LOCALAPPDATA%\\Programs\\stack\\x86_64-windows\\msys2-20161025 C:\\msys64
  - copy %LOCALAPPDATA%\\Programs\\stack\\x86_64-windows\\ghc-8.2.2.installed %LOCALAPPDATA%\\Programs\\stack\\x86_64-windows\\msys2-20161025.installed
  - stack --no-terminal exec pacman -- -Syu --force --noconfirm --noprogressbar
  - stack --no-terminal exec pacman -- -Syu --force --noconfirm --noprogressbar
  - stack --no-terminal build --haddock

test: off
