name: template-haskell-jailbreak
version: 0.0.1
category: Development
stability: alpha
maintainer: Shao Cheng <astrohavoc@gmail.com>
copyright: (c) 2018 Shao Cheng
license: BSD3
github: TerrorJack/template-haskell-jailbreak

extra-source-files:
  - LICENSE
  - README.md
  - CHANGELOG.md

ghc-options: -Wall

dependencies:
  - base

when:
  - condition: os(windows)
    then:
      c-sources: cbits/pargs-win32.c
    else:
      c-sources: cbits/pargs-unix.c

cc-options: -std=c11 -Wall -Wextra -O2 -fPIC

library:
  source-dirs: src
