version: 2
jobs:
  build:
    docker:
      - image: terrorjack/vanilla:haskell
    steps:
      - checkout
      - restore_cache:
          key: stack-work-gen2-
      - run: |
          stack --no-terminal build template-haskell-jailbreak --haddock
          stack --no-terminal test template-haskell-jailbreak-test:andy
      - save_cache:
          key: stack-work-gen2-{{ .BuildNum }}
          paths:
            - /root/.stack
            - .stack-work
            - template-haskell-jailbreak/.stack-work
