name: template-haskell-jailbreak-test
version: 0.0.1

ghc-options: -Wall

dependencies:
  - base
  - ghc
  - template-haskell-jailbreak

tests:
  andy:
    main: andy.hs
    other-extensions:
      - TemplateHaskell
